import { test, expect } from '@playwright/test'
import type { Page } from '@playwright/test'
import { Buffer } from 'node:buffer'
import { readFile } from 'node:fs/promises'
import AxeBuilder from '@axe-core/playwright'
const evidenceDir = process.env.EVIDENCE_DIR ?? '.artifacts/e2e'

async function choose(page: Page, label: string, option: string | RegExp) {
  await page.getByRole('combobox', { name: label, exact: true }).click()
  await page.getByRole('option', { name: option, exact: typeof option === 'string' }).click()
}

test('cápsulas: quitar un filtro conserva las demás selecciones y la búsqueda', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('textbox', { name: 'Buscar cursos' }).fill('Python')
  await choose(page, 'Ubicación', 'Todo el Perú')
  await choose(page, 'Área', 'Python')
  await page.getByRole('button', { name: 'Quitar filtro Área', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Área', exact: true })).toBeFocused()
  await expect(page.getByRole('combobox', { name: 'Área', exact: true })).toHaveText('Área')
  await expect(page.getByRole('combobox', { name: 'Ubicación', exact: true })).toContainText('Todo el Perú')
  await expect(page.getByRole('textbox', { name: 'Buscar cursos' })).toHaveValue('Python')
  await expect(page.locator('.course-card')).toHaveCount(2)
  await page.getByRole('button', { name: 'Limpiar filtros', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Buscar cursos' })).toHaveValue('')
  await expect(page.locator('.filter-bottom')).toContainText('95 oportunidades encontradas')
  await expect(page.getByRole('button', { name: /^Quitar filtro/ })).toHaveCount(0)
})

test('menú: selección por teclado, Escape y foco dentro de ficha', async ({ page }) => {
  await page.goto('./')
  const area = page.getByRole('combobox', { name: 'Área', exact: true })
  await area.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('option', { name: 'Todas las áreas', exact: true })).toBeFocused()
  await page.keyboard.press('End')
  await expect(page.getByRole('option', { name: 'Visualización de datos', exact: true })).toBeFocused()
  await page.keyboard.press('Home')
  await expect(page.getByRole('option', { name: 'Todas las áreas', exact: true })).toBeFocused()
  await page.keyboard.press('p')
  await page.keyboard.press('y')
  await expect(page.getByRole('option', { name: 'Python', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(area).toContainText('Python')
  await expect(area).toBeFocused()
  await page.getByRole('button', { name: 'Ver detalles' }).first().click()
  const route = page.getByRole('combobox', { name: 'Agregar a mi ruta', exact: true })
  await route.click()
  await expect(page.getByRole('listbox')).toBeVisible()
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([])
  await page.keyboard.press('Escape')
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(route).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('popups: tamaños, opciones largas, borde de ventana y colores forzados', async ({ page }, testInfo) => {
  for (const width of [320, 393, 768, 1440]) {
    await page.setViewportSize({ width, height: 960 })
    await page.goto('./')
    for (const label of ['Ubicación', 'Área', 'Institución', 'Gratuidad', 'Inscripción', 'Duración', 'Ordenar oportunidades']) {
      const trigger = page.getByRole('combobox', { name: label, exact: true })
      expect((await trigger.boundingBox())!.height).toBeGreaterThanOrEqual(44)
      await trigger.click()
      const menu = page.getByRole('listbox')
      const box = (await menu.boundingBox())!
      expect(box.x).toBeGreaterThanOrEqual(0)
      expect(box.y).toBeGreaterThanOrEqual(0)
      expect(box.x + box.width).toBeLessThanOrEqual(width)
      expect(box.y + box.height).toBeLessThanOrEqual(960)
      await page.keyboard.press('Escape')
    }
    await choose(page, 'Institución', 'Ministerio de Trabajo y Promoción del Empleo / CAPACÍTA-T (MTPE)')
    expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
    await page.screenshot({ path: `${evidenceDir}/screenshots/${testInfo.project.name}-${width}-long-value.png` })
  }
  await page.emulateMedia({ forcedColors: 'active', reducedMotion: 'reduce' })
  await page.getByRole('combobox', { name: 'Institución', exact: true }).click()
  await expect(page.getByRole('option', { name: 'Todas las instituciones', exact: true })).toBeVisible()
  await page.screenshot({ path: `${evidenceDir}/screenshots/${testInfo.project.name}-forced-colors-menu.png` })
  await page.keyboard.press('Escape')
})


test('select de ficha: estado deshabilitado cuando no hay rutas', async ({ page }) => {
  await page.goto('./#/rutas')
  const downloadWait = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Exportar respaldo de progreso' }).click()
  const download = await downloadWait
  const backup = JSON.parse(await readFile((await download.path())!, 'utf8'))
  backup.data.routes = []
  await page.locator('input[type=file]').setInputFiles({ name: 'sin-rutas.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(backup)) })
  await page.getByRole('button', { name: 'Reemplazar con este respaldo' }).click()
  await page.goto('./')
  await page.getByRole('button', { name: 'Ver detalles' }).first().click()
  const route = page.getByRole('combobox', { name: 'Agregar a mi ruta', exact: true })
  await expect(route).toBeDisabled()
  await expect(route).toContainText('Crea una ruta primero')
  await expect(page.getByRole('dialog').getByRole('button', { name: 'Agregar', exact: true })).toBeDisabled()
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([])
})
test('selects: teclado, ordenamiento y elección de ruta dentro de ficha', async ({ page }) => {
  await page.goto('./')
  const location = page.getByRole('combobox', { name: 'Ubicación', exact: true })
  await location.focus()
  await page.keyboard.press('ArrowDown')
  await expect(page.getByRole('listbox')).toBeVisible()
  await expect(page.getByRole('option', { name: 'Todas las ubicaciones', exact: true })).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(page.getByRole('option', { name: 'Lima', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(location).toContainText('Lima')
  await page.getByRole('button', { name: /Limpiar/ }).click()
  await expect(location).toHaveText('Ubicación')
  await choose(page, 'Ubicación', 'Todo el Perú')
  await choose(page, 'Área', 'Python')
  await choose(page, 'Ordenar oportunidades', 'Mayor duración primero')
  await expect(page.locator('.course-card').first()).toContainText('Fundamentos de Python 2')
  await page.getByRole('button', { name: 'Ver detalles' }).first().click()
  const route = page.getByRole('combobox', { name: 'Agregar a mi ruta', exact: true })
  await choose(page, 'Agregar a mi ruta', /GESTIÓN/)
  await expect(route).toContainText('GESTIÓN')
  await page.getByRole('dialog').getByRole('button', { name: 'Agregar', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Ya está en la ruta', exact: true })).toBeDisabled()
  await page.keyboard.press('Escape')
  await page.goto('./#/rutas')
  await page.getByRole('button', { name: /03 GESTIÓN/ }).click()
  await expect(page.locator('.route-step').last()).toContainText('Fundamentos de Python 2')
})
test('teclado: salto al contenido y cierre de ficha conserva el foco', async ({ page }) => {
  await page.goto('./')
  await page.keyboard.press('Tab')
  await expect(page.getByRole('link', { name: 'Saltar al contenido' })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.locator('main')).toBeFocused()
  await expect(page.locator('h1')).toContainText('Aprender abre')
  const trigger = page.getByRole('button', { name: 'Ver detalles' }).first()
  await trigger.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(trigger).toBeFocused()
})
test('catálogo: filtros combinados, favoritos y ficha accesible', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('./')
  await expect(page.getByRole('heading', { name: /Aprender abre/ })).toBeVisible()
  await page.getByRole('textbox', { name: 'Buscar cursos' }).fill('Python')
  await choose(page, 'Ubicación', 'Todo el Perú')
  await choose(page, 'Área', 'Python')
  await choose(page, 'Duración', '20 horas o más')
  await expect(page.locator('.course-card')).toHaveCount(2)
  await page.getByRole('button', { name: 'Guardar Fundamentos de Python 1', exact: true }).click()
  await page.getByLabel('Solo mis guardados').check()
  await expect(page.locator('.course-card')).toHaveCount(1)
  await page.getByRole('button', { name: 'Ver detalles' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('link', { name: 'Ir a la fuente oficial' })).toHaveAttribute('href', /^https:/)
  const axe = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
  expect(axe.violations).toEqual([])
  await page.getByRole('button', { name: 'Cerrar detalles' }).click()
  await page.reload()
  await page.getByLabel('Solo mis guardados').check()
  await expect(page.locator('.course-card')).toHaveCount(1)
  expect(errors).toEqual([])
})
test('rutas: progreso persiste, reordenamiento y creación personal', async ({ page }) => {
  await page.goto('./#/rutas')
  const complete = page.getByRole('checkbox', { name: 'Completar Excel básico', exact: true })
  await complete.check()
  await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '8')
  await page.getByRole('button', { name: 'Bajar Excel básico', exact: true }).click()
  await expect(page.locator('.route-step').first()).toContainText('Excel intermedio')
  await page.reload()
  await expect(complete).toBeChecked()
  await expect(page.locator('.route-step').first()).toContainText('Excel intermedio')
  await page.getByRole('button', { name: 'Crear una ruta', exact: true }).click()
  await page.getByLabel('Nombre de la nueva ruta').fill('Mi camino Python')
  await page.getByRole('button', { name: 'Crear ruta', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Mi camino Python' })).toBeVisible()
  await choose(page, 'Agregar un curso', 'Fundamentos de Python 1 — Cisco')
  await page.getByRole('button', { name: 'Agregar', exact: true }).click()
  await expect(page.locator('.route-step')).toHaveCount(1)
  await page.getByRole('button', { name: 'Quitar Fundamentos de Python 1 de esta ruta', exact: true }).click()
  await expect(page.locator('.route-step')).toHaveCount(0)
})
test('respaldo: exportación, importación revisable y rechazo de archivo ajeno', async ({ page }) => {
  await page.goto('./#/rutas')
  await page.getByRole('checkbox', { name: 'Completar Excel básico', exact: true }).check()
  const downloadWait = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Exportar respaldo de progreso' }).click()
  const download = await downloadWait
  const file = await download.path()
  await page.getByRole('checkbox', { name: 'Completar Excel básico', exact: true }).uncheck()
  await page.locator('input[type=file]').setInputFiles(file!)
  await expect(page.getByRole('dialog')).toContainText('Importar tu progreso')
  await page.getByRole('button', { name: 'Reemplazar con este respaldo' }).click()
  await expect(page.getByRole('checkbox', { name: 'Completar Excel básico', exact: true })).toBeChecked()
  await page.locator('input[type=file]').setInputFiles({ name: 'ajeno.json', mimeType: 'application/json', buffer: Buffer.from('{}') })
  await expect(page.getByRole('status')).toContainText('Selecciona un respaldo')
  await expect(page.getByRole('checkbox', { name: 'Completar Excel básico', exact: true })).toBeChecked()
})
test('cinco vistas, gráficos, radar y navegación en subruta sin errores', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  for (const route of ['', '#/analisis', '#/recomendados', '#/rutas', '#/radar']) {
    await page.goto(`./${route}`)
    await expect(page.locator('h1')).toBeVisible()
    if (route.includes('analisis')) await expect(page.getByRole('heading', { name: '¿Qué puedes aprender?' })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)).toBe(false)
    const axe = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
    expect(axe.violations.map(v => ({ id: v.id, nodes: v.nodes.map(n => ({ target: n.target, issue: n.failureSummary })) }))).toEqual([])
    await page.screenshot({ path: `${evidenceDir}/screenshots/${testInfo.project.name}-${route.replace('#/', '') || 'catalogo'}.png`, fullPage: true })
  }
  await page.locator('.radar-card').first().getByRole('button', { name: 'Seguir', exact: true }).click()
  await page.getByLabel(/Solo las que sigo/).check()
  await expect(page.locator('.radar-card')).toHaveCount(1)
  await page.getByRole('button', { name: 'Marcar revisado' }).click()
  await expect(page.locator('.radar-card')).not.toContainText('Revisión personal: Pendiente')
  await page.reload()
  await page.getByLabel(/Solo las que sigo/).check()
  await expect(page.locator('.radar-card')).toHaveCount(1)
  expect(errors).toEqual([])
})
