import { lazy, Suspense, useRef, useState } from 'react'
import { NavLink, Route, Routes, useLocation } from 'react-router-dom'
import { ArrowDownToLine, ArrowRight, ArrowUpFromLine, ArrowUpRight, BookOpen, Bookmark, ChartNoAxesCombined, Check, CircleHelp, Compass, GraduationCap, LayoutGrid, List, ListOrdered, Radar, ShieldCheck, Sparkles } from 'lucide-react'
import { catalog, courseById, defaultFilters, filterCourses, safeUrl } from './lib/catalog'
import type { Filters as FilterState } from './lib/catalog'
import { makeBackup, parseBackup } from './lib/progress'
import type { PersonalData } from './lib/progress'
import { storageProblem, usePersonal } from './lib/store'
import { Button } from './components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogTitle } from './components/ui/dialog'
import Filters from './components/Filters'
import CourseCard from './components/CourseCard'
import CourseDetail from './components/CourseDetail'
import { SelectField } from './components/ui/select-field'
import RoutesView from './views/RoutesView'
import RadarView from './views/RadarView'
const Analytics = lazy(() => import('./views/Analytics'))
const navigation = [ { to: '/', label: 'Explorar catálogo', icon: Compass }, { to: '/analisis', label: 'Panorama de oferta', icon: ChartNoAxesCombined }, { to: '/recomendados', label: 'TOP 15 recomendados', icon: Sparkles }, { to: '/rutas', label: 'Mis rutas', icon: ListOrdered }, { to: '/radar', label: 'Radar institucional', icon: Radar } ]
const pageInfo: Record<string, [string, string]> = { '/analisis': ['Una mirada a las oportunidades.', 'Explora la oferta de formación con datos, contexto y fuentes.'], '/recomendados': ['15 formas de dar el siguiente paso.', 'Una selección para aprender con propósito y fortalecer tu perfil.'], '/rutas': ['Las grandes metas empiezan con un paso.', 'Elige tu dirección, organiza tu aprendizaje y celebra cada avance.'], '/radar': ['Que la próxima oportunidad te encuentre.', 'Sigue instituciones y organiza la revisión de nuevas convocatorias.'] }
export default function App() {
  const location = useLocation()
  const personal = usePersonal()
  const [filters, setFilters] = useState<FilterState>({ ...defaultFilters })
  const [opened, setOpened] = useState<string | null>(null)
  const [layout, setLayout] = useState<'grid' | 'list'>('grid')
  const [visibleCount, setVisibleCount] = useState(12)
  const [message, setMessage] = useState('')
  const [backup, setBackup] = useState<PersonalData | null>(null)
  const [help, setHelp] = useState(false)
  const upload = useRef<HTMLInputElement>(null)
  const notify = (text: string) => setMessage(text)
  const results = filterCourses(filters, personal.favorites)
  const changeFilters = (value: FilterState) => { setFilters(value); setVisibleCount(12) }
  const info = pageInfo[location.pathname]
  function downloadBackup() {
    const blob = new Blob([JSON.stringify(makeBackup(personal), null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob), anchor = document.createElement('a')
    anchor.href = url; anchor.download = `educalibre-progreso-${new Date().toISOString().slice(0, 10)}.json`; anchor.click(); URL.revokeObjectURL(url)
    notify('Respaldo exportado. Guárdalo para recuperar tu progreso.')
  }
  return <div className="app-shell"><a className="skip-link" href="#main-content" onClick={e => { e.preventDefault(); document.getElementById('main-content')?.focus() }}>Saltar al contenido</a>
    <aside className="sidebar"><NavLink to="/" className="brand" aria-label="EducaLibre inicio"><span className="brand-mark"><BookOpen size={24} /></span><span>Educa<span>Libre</span><small>APRENDE. AVANZA. TRANSFORMA.</small></span></NavLink><div className="sidebar-label">TU ESPACIO DE APRENDIZAJE</div><nav aria-label="Navegación principal">{navigation.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} end={to === '/'} className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}><Icon size={19} /><span>{label}</span>{to === '/recomendados' && <small>15</small>}</NavLink>)}</nav><div className="sidebar-saved"><Bookmark size={16} /><span>{personal.favorites.length} oportunidades guardadas</span></div><div className="sidebar-bottom"><div className="growth-card"><span className="growth-art" aria-hidden="true">✳</span><strong>Tu futuro se construye<br />aprendiendo.</strong><p>Cada nueva habilidad es una puerta que se abre.</p><NavLink to="/rutas">Encuentra tu ruta<ArrowRight size={16} /></NavLink></div><button className="help-button" onClick={() => setHelp(true)}><CircleHelp size={17} />Acerca del catálogo</button><span className="sidebar-credit">Hecho para aprender desde Perú <span aria-hidden="true">↗</span></span></div></aside>
    <div className="main-shell"><header className="topbar"><span className="breadcrumb">Tu espacio <span>/</span> <strong>{navigation.find(n => n.to === location.pathname)?.label ?? 'Explorar catálogo'}</strong></span><div className="topbar-actions"><span className="local-storage-tag"><span />Progreso local</span><Button variant="ghost" size="icon" aria-label="Exportar respaldo de progreso" title="Exportar progreso" onClick={downloadBackup}><ArrowDownToLine size={18} /></Button><Button variant="ghost" size="icon" aria-label="Importar respaldo de progreso" title="Importar progreso" onClick={() => upload.current?.click()}><ArrowUpFromLine size={18} /></Button><span className="avatar" aria-hidden="true">TÚ</span></div><input className="sr-only" aria-label="Archivo de respaldo de progreso" type="file" tabIndex={-1} accept=".json,application/json" ref={upload} onChange={async e => { const file = e.target.files?.[0]; e.target.value = ''; if (!file) return; try { if (file.size > 1_000_000) throw new Error('El respaldo supera el límite de 1 MB.'); setBackup(parseBackup(await file.text())) } catch (error) { notify(error instanceof Error ? error.message : 'No se pudo leer el archivo.') } }} /></header>
    <main id="main-content" tabIndex={-1} className="page"><div className="page-intro"><span className="eyebrow">FORMACIÓN SIN BARRERAS</span><div className="source-date"><ShieldCheck size={14} />Fuentes oficiales · Corte 07 oct. 2026</div></div>
      {location.pathname === '/' ? <section className="hero"><div className="hero-copy"><h1>Aprender abre<br /><span>nuevas posibilidades.</span></h1><p>Encuentra tu próxima habilidad entre oportunidades gratuitas de Perú y el mundo. Tu siguiente paso empieza aquí.</p><div className="hero-pills"><span><Check size={14} />95 oportunidades</span><span><Check size={14} />A tu ritmo</span><span><Check size={14} />Desde Perú</span></div></div><div className="hero-map" aria-hidden="true"><span className="hero-map-label">UN CAMINO HECHO PARA TI</span><svg viewBox="0 0 350 175"><path d="M35 139 C80 139 70 88 120 88 S173 120 217 70 S247 36 298 36" fill="none" stroke="var(--primary-line)" strokeWidth="2" strokeDasharray="5 5" /><circle cx="35" cy="139" r="6" fill="var(--primary)" /><circle cx="120" cy="88" r="6" fill="var(--primary)" /><circle cx="217" cy="70" r="6" fill="var(--primary)" /><circle cx="298" cy="36" r="18" fill="var(--primary-soft)" /><path d="m290 36 5 5 11-11" fill="none" stroke="var(--primary)" strokeWidth="2" /></svg><span className="map-label first">Explora</span><span className="map-label second">Aprende</span><span className="map-label third">Crece</span><div className="floating-course"><span><GraduationCap size={22} /></span><div><small>Tu próximo capítulo</small><strong>Una habilidad, muchas puertas.</strong></div></div></div></section> : <section className="view-heading"><h1>{info?.[0] ?? 'Encuentra tu próximo paso.'}</h1><p>{info?.[1] ?? 'Explora el catálogo de oportunidades.'}</p></section>}
      {storageProblem && <p role="alert" className="context-note">{storageProblem}</p>}
      <Routes>
        <Route path="/" element={<><Filters value={filters} onChange={changeFilters} count={results.length} /><div className="section-toolbar"><div><h2>Oportunidades para ti</h2><p>Elige una habilidad. Abre una nueva puerta.</p></div><div className="catalog-tools"><label><span className="sr-only">Ordenar oportunidades</span><SelectField label="Ordenar oportunidades" value={filters.sort} onValueChange={next => changeFilters({ ...filters, sort: next })} options={[{ value: 'recommended', label: 'Recomendados primero' }, { value: 'name', label: 'Nombre A–Z' }, { value: 'duration', label: 'Mayor duración primero' }]} /></label><div className="layout-toggle"><Button size="icon" variant={layout === 'grid' ? 'secondary' : 'ghost'} aria-label="Vista de tarjetas" aria-pressed={layout === 'grid'} onClick={() => setLayout('grid')}><LayoutGrid size={17} /></Button><Button size="icon" variant={layout === 'list' ? 'secondary' : 'ghost'} aria-label="Vista de lista" aria-pressed={layout === 'list'} onClick={() => setLayout('list')}><List size={17} /></Button></div></div></div><div className={`course-grid ${layout === 'list' ? 'course-list' : ''}`}>{results.slice(0, visibleCount).map(course => <CourseCard key={course.id} course={course} onOpen={setOpened} />)}</div>{!results.length && <div className="empty-state"><Compass size={32} /><h3>Tu próxima oportunidad aún no aparece</h3><p>Prueba otro término o amplía los filtros.</p><Button variant="secondary" onClick={() => changeFilters({ ...defaultFilters })}>Restablecer filtros</Button></div>}{results.length > visibleCount && <div className="load-more"><p>Mostrando {Math.min(visibleCount, results.length)} de {results.length} oportunidades</p><Button variant="secondary" onClick={() => setVisibleCount(n => n + 12)}>Explorar más oportunidades<ArrowRight size={16} /></Button></div>}</>} />
        <Route path="/analisis" element={<><Filters value={filters} onChange={changeFilters} count={results.length} /><Suspense fallback={<p role="status">Preparando el panorama de oferta…</p>}><Analytics courses={results} /></Suspense></>} />
        <Route path="/recomendados" element={<><div className="selection-banner"><Sparkles size={24} /><p>Seleccionados por utilidad práctica, trayectoria de la institución, duración y condiciones de acceso. La credencial y sus costos se muestran por separado.</p></div><div className="course-grid top-grid">{catalog.top15.map(rec => <CourseCard key={rec.course_id} course={courseById.get(rec.course_id)!} rank={rec.rank} onOpen={setOpened} />)}</div></>} />
        <Route path="/rutas" element={<RoutesView onOpen={setOpened} notify={notify} />} />
        <Route path="/radar" element={<RadarView notify={notify} />} />
        <Route path="*" element={<div className="empty-state"><h1>Este camino no existe todavía</h1><Button asChild><NavLink to="/">Volver al catálogo</NavLink></Button></div>} />
      </Routes>
      <footer className="page-footer"><span>EducaLibre · Aprender es avanzar.</span><button onClick={() => setHelp(true)}>Fuentes, criterios y alcance<ArrowUpRight size={14} /></button></footer>
    </main></div>
    {message && <div className="toast" role="status"><Check size={18} /><span>{message}</span><button aria-label="Cerrar mensaje" onClick={() => setMessage('')}>×</button></div>}
    <CourseDetail id={opened} onClose={() => setOpened(null)} notify={notify} />
    <Dialog open={!!backup} onOpenChange={open => { if (!open) setBackup(null) }}><DialogContent className="small-dialog"><DialogTitle>Importar tu progreso</DialogTitle><DialogDescription>Este respaldo reemplazará los favoritos, rutas, cursos completados y seguimiento guardados en este navegador.</DialogDescription><p>{backup?.routes.length} rutas · {backup?.completed.length} completados · {backup?.favorites.length} guardados</p><div className="detail-actions"><Button onClick={() => { if (backup) { personal.replaceData(backup); setBackup(null); notify('Tu progreso se importó correctamente.') } }}>Reemplazar con este respaldo</Button><Button variant="secondary" onClick={() => setBackup(null)}>Cancelar</Button></div></DialogContent></Dialog>
    <Dialog open={help} onOpenChange={setHelp}><DialogContent><DialogTitle>Aprender con información clara</DialogTitle><DialogDescription>Este catálogo transforma una investigación de fuentes públicas realizada el 7 de octubre de 2026.</DialogDescription><p>95 oportunidades: 21 vinculadas a Lima, 30 adicionales del programa nacional MTPE y 44 internacionales. No son treinta universidades regionales ni una muestra del mercado laboral.</p><ul className="help-list">{catalog.limitations.map(item => <li key={item}>{item}</li>)}</ul><p>El progreso es local y puede perderse al borrar datos del navegador. Exporta un respaldo. Marcar completado es tu seguimiento personal; no acredita la emisión de una credencial.</p><p>El cierre de una convocatoria se calcula a partir del plazo publicado, cuando existe. Los demás estados corresponden a la fecha del informe.</p><Button asChild variant="secondary"><a href={safeUrl('https://capacitacionlaboral.trabajo.gob.pe/cursos/') ?? undefined} target="_blank" rel="noopener noreferrer">Consultar CAPACÍTA-T<ArrowUpRight size={16} /></a></Button></DialogContent></Dialog>
  </div>
}
